[package]
name = "atsssvt"
version = "0.1.0"
authors = ["Felix Kaaman <trundmatu@gmail.com>"]

[dependencies]
bitflags = "1.0"
term = "0.4.6"
derivative = "1.0"
svg = "*"

[dependencies.winapi]
version = "0.3"
features = ["everything"]
